  .balign 4, 0
.global DirectSoundWaveData_unk_08110294
DirectSoundWaveData_unk_08110294:
  .incbin "sound/direct_sound_samples/unk_08110294.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08110c24
DirectSoundWaveData_unk_08110c24:
  .incbin "sound/direct_sound_samples/unk_08110c24.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08110e88
DirectSoundWaveData_unk_08110e88:
  .incbin "sound/direct_sound_samples/unk_08110e88.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08113154
DirectSoundWaveData_unk_08113154:
  .incbin "sound/direct_sound_samples/unk_08113154.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08113840
DirectSoundWaveData_unk_08113840:
  .incbin "sound/direct_sound_samples/unk_08113840.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08114c1c
DirectSoundWaveData_unk_08114c1c:
  .incbin "sound/direct_sound_samples/unk_08114c1c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08115430
DirectSoundWaveData_unk_08115430:
  .incbin "sound/direct_sound_samples/unk_08115430.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08117e68
DirectSoundWaveData_unk_08117e68:
  .incbin "sound/direct_sound_samples/unk_08117e68.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081182f4
DirectSoundWaveData_unk_081182f4:
  .incbin "sound/direct_sound_samples/unk_081182f4.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08119ae8
DirectSoundWaveData_unk_08119ae8:
  .incbin "sound/direct_sound_samples/unk_08119ae8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0811a730
DirectSoundWaveData_unk_0811a730:
  .incbin "sound/direct_sound_samples/unk_0811a730.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0811b9ac
DirectSoundWaveData_unk_0811b9ac:
  .incbin "sound/direct_sound_samples/unk_0811b9ac.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08122690
DirectSoundWaveData_unk_08122690:
  .incbin "sound/direct_sound_samples/unk_08122690.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081233b0
DirectSoundWaveData_unk_081233b0:
  .incbin "sound/direct_sound_samples/unk_081233b0.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081239a8
DirectSoundWaveData_unk_081239a8:
  .incbin "sound/direct_sound_samples/unk_081239a8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0812548c
DirectSoundWaveData_unk_0812548c:
  .incbin "sound/direct_sound_samples/unk_0812548c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08126dc4
DirectSoundWaveData_unk_08126dc4:
  .incbin "sound/direct_sound_samples/unk_08126dc4.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08128358
DirectSoundWaveData_unk_08128358:
  .incbin "sound/direct_sound_samples/unk_08128358.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0812944c
DirectSoundWaveData_unk_0812944c:
  .incbin "sound/direct_sound_samples/unk_0812944c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0812a598
DirectSoundWaveData_unk_0812a598:
  .incbin "sound/direct_sound_samples/unk_0812a598.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0812d018
DirectSoundWaveData_unk_0812d018:
  .incbin "sound/direct_sound_samples/unk_0812d018.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0812e01c
DirectSoundWaveData_unk_0812e01c:
  .incbin "sound/direct_sound_samples/unk_0812e01c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0812fa98
DirectSoundWaveData_unk_0812fa98:
  .incbin "sound/direct_sound_samples/unk_0812fa98.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081314ac
DirectSoundWaveData_unk_081314ac:
  .incbin "sound/direct_sound_samples/unk_081314ac.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08132a30
DirectSoundWaveData_unk_08132a30:
  .incbin "sound/direct_sound_samples/unk_08132a30.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08134538
DirectSoundWaveData_unk_08134538:
  .incbin "sound/direct_sound_samples/unk_08134538.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08135460
DirectSoundWaveData_unk_08135460:
  .incbin "sound/direct_sound_samples/unk_08135460.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08135df4
DirectSoundWaveData_unk_08135df4:
  .incbin "sound/direct_sound_samples/unk_08135df4.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081371c4
DirectSoundWaveData_unk_081371c4:
  .incbin "sound/direct_sound_samples/unk_081371c4.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08137d38
DirectSoundWaveData_unk_08137d38:
  .incbin "sound/direct_sound_samples/unk_08137d38.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08139c10
DirectSoundWaveData_unk_08139c10:
  .incbin "sound/direct_sound_samples/unk_08139c10.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0813a868
DirectSoundWaveData_unk_0813a868:
  .incbin "sound/direct_sound_samples/unk_0813a868.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0813acb8
DirectSoundWaveData_unk_0813acb8:
  .incbin "sound/direct_sound_samples/unk_0813acb8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0813b20c
DirectSoundWaveData_unk_0813b20c:
  .incbin "sound/direct_sound_samples/unk_0813b20c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0813c44c
DirectSoundWaveData_unk_0813c44c:
  .incbin "sound/direct_sound_samples/unk_0813c44c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0813dabc
DirectSoundWaveData_unk_0813dabc:
  .incbin "sound/direct_sound_samples/unk_0813dabc.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08141fa0
DirectSoundWaveData_unk_08141fa0:
  .incbin "sound/direct_sound_samples/unk_08141fa0.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08143110
DirectSoundWaveData_unk_08143110:
  .incbin "sound/direct_sound_samples/unk_08143110.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08143d90
DirectSoundWaveData_unk_08143d90:
  .incbin "sound/direct_sound_samples/unk_08143d90.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0814508c
DirectSoundWaveData_unk_0814508c:
  .incbin "sound/direct_sound_samples/unk_0814508c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08145da4
DirectSoundWaveData_unk_08145da4:
  .incbin "sound/direct_sound_samples/unk_08145da4.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08148eb8
DirectSoundWaveData_unk_08148eb8:
  .incbin "sound/direct_sound_samples/unk_08148eb8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0814c8a0
DirectSoundWaveData_unk_0814c8a0:
  .incbin "sound/direct_sound_samples/unk_0814c8a0.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081501c8
DirectSoundWaveData_unk_081501c8:
  .incbin "sound/direct_sound_samples/unk_081501c8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0815a450
DirectSoundWaveData_unk_0815a450:
  .incbin "sound/direct_sound_samples/unk_0815a450.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0815ace4
DirectSoundWaveData_unk_0815ace4:
  .incbin "sound/direct_sound_samples/unk_0815ace4.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0815b6c4
DirectSoundWaveData_unk_0815b6c4:
  .incbin "sound/direct_sound_samples/unk_0815b6c4.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0815d274
DirectSoundWaveData_unk_0815d274:
  .incbin "sound/direct_sound_samples/unk_0815d274.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0815e2cc
DirectSoundWaveData_unk_0815e2cc:
  .incbin "sound/direct_sound_samples/unk_0815e2cc.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0815f970
DirectSoundWaveData_unk_0815f970:
  .incbin "sound/direct_sound_samples/unk_0815f970.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08160ea4
DirectSoundWaveData_unk_08160ea4:
  .incbin "sound/direct_sound_samples/unk_08160ea4.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08161738
DirectSoundWaveData_unk_08161738:
  .incbin "sound/direct_sound_samples/unk_08161738.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0816390c
DirectSoundWaveData_unk_0816390c:
  .incbin "sound/direct_sound_samples/unk_0816390c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08166950
DirectSoundWaveData_unk_08166950:
  .incbin "sound/direct_sound_samples/unk_08166950.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081683d0
DirectSoundWaveData_unk_081683d0:
  .incbin "sound/direct_sound_samples/unk_081683d0.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08169a80
DirectSoundWaveData_unk_08169a80:
  .incbin "sound/direct_sound_samples/unk_08169a80.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0816a764
DirectSoundWaveData_unk_0816a764:
  .incbin "sound/direct_sound_samples/unk_0816a764.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0816b794
DirectSoundWaveData_unk_0816b794:
  .incbin "sound/direct_sound_samples/unk_0816b794.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0816e040
DirectSoundWaveData_unk_0816e040:
  .incbin "sound/direct_sound_samples/unk_0816e040.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081702e8
DirectSoundWaveData_unk_081702e8:
  .incbin "sound/direct_sound_samples/unk_081702e8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081735f0
DirectSoundWaveData_unk_081735f0:
  .incbin "sound/direct_sound_samples/unk_081735f0.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08174ca0
DirectSoundWaveData_unk_08174ca0:
  .incbin "sound/direct_sound_samples/unk_08174ca0.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0817595c
DirectSoundWaveData_unk_0817595c:
  .incbin "sound/direct_sound_samples/unk_0817595c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08176c20
DirectSoundWaveData_unk_08176c20:
  .incbin "sound/direct_sound_samples/unk_08176c20.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08178940
DirectSoundWaveData_unk_08178940:
  .incbin "sound/direct_sound_samples/unk_08178940.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0817b640
DirectSoundWaveData_unk_0817b640:
  .incbin "sound/direct_sound_samples/unk_0817b640.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0817c708
DirectSoundWaveData_unk_0817c708:
  .incbin "sound/direct_sound_samples/unk_0817c708.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0817dae8
DirectSoundWaveData_unk_0817dae8:
  .incbin "sound/direct_sound_samples/unk_0817dae8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0817f1bc
DirectSoundWaveData_unk_0817f1bc:
  .incbin "sound/direct_sound_samples/unk_0817f1bc.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0818343c
DirectSoundWaveData_unk_0818343c:
  .incbin "sound/direct_sound_samples/unk_0818343c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0818508c
DirectSoundWaveData_unk_0818508c:
  .incbin "sound/direct_sound_samples/unk_0818508c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08187bf0
DirectSoundWaveData_unk_08187bf0:
  .incbin "sound/direct_sound_samples/unk_08187bf0.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08189378
DirectSoundWaveData_unk_08189378:
  .incbin "sound/direct_sound_samples/unk_08189378.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0818ac48
DirectSoundWaveData_unk_0818ac48:
  .incbin "sound/direct_sound_samples/unk_0818ac48.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0818e210
DirectSoundWaveData_unk_0818e210:
  .incbin "sound/direct_sound_samples/unk_0818e210.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0818f1f4
DirectSoundWaveData_unk_0818f1f4:
  .incbin "sound/direct_sound_samples/unk_0818f1f4.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08190f1c
DirectSoundWaveData_unk_08190f1c:
  .incbin "sound/direct_sound_samples/unk_08190f1c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081924bc
DirectSoundWaveData_unk_081924bc:
  .incbin "sound/direct_sound_samples/unk_081924bc.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081969c0
DirectSoundWaveData_unk_081969c0:
  .incbin "sound/direct_sound_samples/unk_081969c0.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08197938
DirectSoundWaveData_unk_08197938:
  .incbin "sound/direct_sound_samples/unk_08197938.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08198864
DirectSoundWaveData_unk_08198864:
  .incbin "sound/direct_sound_samples/unk_08198864.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0819a3c8
DirectSoundWaveData_unk_0819a3c8:
  .incbin "sound/direct_sound_samples/unk_0819a3c8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0819c514
DirectSoundWaveData_unk_0819c514:
  .incbin "sound/direct_sound_samples/unk_0819c514.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0819d6d8
DirectSoundWaveData_unk_0819d6d8:
  .incbin "sound/direct_sound_samples/unk_0819d6d8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081a04c8
DirectSoundWaveData_unk_081a04c8:
  .incbin "sound/direct_sound_samples/unk_081a04c8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081a12e4
DirectSoundWaveData_unk_081a12e4:
  .incbin "sound/direct_sound_samples/unk_081a12e4.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081a2ee4
DirectSoundWaveData_unk_081a2ee4:
  .incbin "sound/direct_sound_samples/unk_081a2ee4.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081a4af0
DirectSoundWaveData_unk_081a4af0:
  .incbin "sound/direct_sound_samples/unk_081a4af0.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081a71f8
DirectSoundWaveData_unk_081a71f8:
  .incbin "sound/direct_sound_samples/unk_081a71f8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081a91ac
DirectSoundWaveData_unk_081a91ac:
  .incbin "sound/direct_sound_samples/unk_081a91ac.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081a9e24
DirectSoundWaveData_unk_081a9e24:
  .incbin "sound/direct_sound_samples/unk_081a9e24.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081aafc4
DirectSoundWaveData_unk_081aafc4:
  .incbin "sound/direct_sound_samples/unk_081aafc4.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081ac48c
DirectSoundWaveData_unk_081ac48c:
  .incbin "sound/direct_sound_samples/unk_081ac48c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081ade90
DirectSoundWaveData_unk_081ade90:
  .incbin "sound/direct_sound_samples/unk_081ade90.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081b23c4
DirectSoundWaveData_unk_081b23c4:
  .incbin "sound/direct_sound_samples/unk_081b23c4.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081b4a2c
DirectSoundWaveData_unk_081b4a2c:
  .incbin "sound/direct_sound_samples/unk_081b4a2c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081b57f0
DirectSoundWaveData_unk_081b57f0:
  .incbin "sound/direct_sound_samples/unk_081b57f0.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081b66d8
DirectSoundWaveData_unk_081b66d8:
  .incbin "sound/direct_sound_samples/unk_081b66d8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081b9144
DirectSoundWaveData_unk_081b9144:
  .incbin "sound/direct_sound_samples/unk_081b9144.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081bb7bc
DirectSoundWaveData_unk_081bb7bc:
  .incbin "sound/direct_sound_samples/unk_081bb7bc.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081be04c
DirectSoundWaveData_unk_081be04c:
  .incbin "sound/direct_sound_samples/unk_081be04c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081c1a30
DirectSoundWaveData_unk_081c1a30:
  .incbin "sound/direct_sound_samples/unk_081c1a30.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081c320c
DirectSoundWaveData_unk_081c320c:
  .incbin "sound/direct_sound_samples/unk_081c320c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081c3e54
DirectSoundWaveData_unk_081c3e54:
  .incbin "sound/direct_sound_samples/unk_081c3e54.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081c7a64
DirectSoundWaveData_unk_081c7a64:
  .incbin "sound/direct_sound_samples/unk_081c7a64.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081c97e0
DirectSoundWaveData_unk_081c97e0:
  .incbin "sound/direct_sound_samples/unk_081c97e0.bin"

@;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

  .balign 4, 0
.global DirectSoundWaveData_unk_081cbd58
DirectSoundWaveData_unk_081cbd58:
  .incbin "sound/direct_sound_samples/unk_081cbd58.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081cdfa8
DirectSoundWaveData_unk_081cdfa8:
  .incbin "sound/direct_sound_samples/unk_081cdfa8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081d1640
DirectSoundWaveData_unk_081d1640:
  .incbin "sound/direct_sound_samples/unk_081d1640.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081d550c
DirectSoundWaveData_unk_081d550c:
  .incbin "sound/direct_sound_samples/unk_081d550c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081d6540
DirectSoundWaveData_unk_081d6540:
  .incbin "sound/direct_sound_samples/unk_081d6540.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081d6c70
DirectSoundWaveData_unk_081d6c70:
  .incbin "sound/direct_sound_samples/unk_081d6c70.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081d9f1c
DirectSoundWaveData_unk_081d9f1c:
  .incbin "sound/direct_sound_samples/unk_081d9f1c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081de3ec
DirectSoundWaveData_unk_081de3ec:
  .incbin "sound/direct_sound_samples/unk_081de3ec.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081e2060
DirectSoundWaveData_unk_081e2060:
  .incbin "sound/direct_sound_samples/unk_081e2060.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081e3bf0
DirectSoundWaveData_unk_081e3bf0:
  .incbin "sound/direct_sound_samples/unk_081e3bf0.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081e87e8
DirectSoundWaveData_unk_081e87e8:
  .incbin "sound/direct_sound_samples/unk_081e87e8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081ed10c
DirectSoundWaveData_unk_081ed10c:
  .incbin "sound/direct_sound_samples/unk_081ed10c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081f1bf0
DirectSoundWaveData_unk_081f1bf0:
  .incbin "sound/direct_sound_samples/unk_081f1bf0.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081f3220
DirectSoundWaveData_unk_081f3220:
  .incbin "sound/direct_sound_samples/unk_081f3220.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081f4cb8
DirectSoundWaveData_unk_081f4cb8:
  .incbin "sound/direct_sound_samples/unk_081f4cb8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081f675c
DirectSoundWaveData_unk_081f675c:
  .incbin "sound/direct_sound_samples/unk_081f675c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081fbaf0
DirectSoundWaveData_unk_081fbaf0:
  .incbin "sound/direct_sound_samples/unk_081fbaf0.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_081fcc90
DirectSoundWaveData_unk_081fcc90:
  .incbin "sound/direct_sound_samples/unk_081fcc90.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08200260
DirectSoundWaveData_unk_08200260:
  .incbin "sound/direct_sound_samples/unk_08200260.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0820195c
DirectSoundWaveData_unk_0820195c:
  .incbin "sound/direct_sound_samples/unk_0820195c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082066d8
DirectSoundWaveData_unk_082066d8:
  .incbin "sound/direct_sound_samples/unk_082066d8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0820b9dc
DirectSoundWaveData_unk_0820b9dc:
  .incbin "sound/direct_sound_samples/unk_0820b9dc.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08212ca4
DirectSoundWaveData_unk_08212ca4:
  .incbin "sound/direct_sound_samples/unk_08212ca4.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08216898
DirectSoundWaveData_unk_08216898:
  .incbin "sound/direct_sound_samples/unk_08216898.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0821a5ac
DirectSoundWaveData_unk_0821a5ac:
  .incbin "sound/direct_sound_samples/unk_0821a5ac.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08220d20
DirectSoundWaveData_unk_08220d20:
  .incbin "sound/direct_sound_samples/unk_08220d20.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0822171c
DirectSoundWaveData_unk_0822171c:
  .incbin "sound/direct_sound_samples/unk_0822171c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08222680
DirectSoundWaveData_unk_08222680:
  .incbin "sound/direct_sound_samples/unk_08222680.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08223c34
DirectSoundWaveData_unk_08223c34:
  .incbin "sound/direct_sound_samples/unk_08223c34.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082245c4
DirectSoundWaveData_unk_082245c4:
  .incbin "sound/direct_sound_samples/unk_082245c4.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0822a250
DirectSoundWaveData_unk_0822a250:
  .incbin "sound/direct_sound_samples/unk_0822a250.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0822e24c
DirectSoundWaveData_unk_0822e24c:
  .incbin "sound/direct_sound_samples/unk_0822e24c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08231c60
DirectSoundWaveData_unk_08231c60:
  .incbin "sound/direct_sound_samples/unk_08231c60.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0823856c
DirectSoundWaveData_unk_0823856c:
  .incbin "sound/direct_sound_samples/unk_0823856c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08238d74
DirectSoundWaveData_unk_08238d74:
  .incbin "sound/direct_sound_samples/unk_08238d74.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0823c4d4
DirectSoundWaveData_unk_0823c4d4:
  .incbin "sound/direct_sound_samples/unk_0823c4d4.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0823e9f8
DirectSoundWaveData_unk_0823e9f8:
  .incbin "sound/direct_sound_samples/unk_0823e9f8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082410fc
DirectSoundWaveData_unk_082410fc:
  .incbin "sound/direct_sound_samples/unk_082410fc.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08245c38
DirectSoundWaveData_unk_08245c38:
  .incbin "sound/direct_sound_samples/unk_08245c38.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0824c608
DirectSoundWaveData_unk_0824c608:
  .incbin "sound/direct_sound_samples/unk_0824c608.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0824e3cc
DirectSoundWaveData_unk_0824e3cc:
  .incbin "sound/direct_sound_samples/unk_0824e3cc.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08250490
DirectSoundWaveData_unk_08250490:
  .incbin "sound/direct_sound_samples/unk_08250490.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0825403c
DirectSoundWaveData_unk_0825403c:
  .incbin "sound/direct_sound_samples/unk_0825403c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08255ac0
DirectSoundWaveData_unk_08255ac0:
  .incbin "sound/direct_sound_samples/unk_08255ac0.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08257794
DirectSoundWaveData_unk_08257794:
  .incbin "sound/direct_sound_samples/unk_08257794.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0825b8d8
DirectSoundWaveData_unk_0825b8d8:
  .incbin "sound/direct_sound_samples/unk_0825b8d8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0825dbbc
DirectSoundWaveData_unk_0825dbbc:
  .incbin "sound/direct_sound_samples/unk_0825dbbc.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08261a54
DirectSoundWaveData_unk_08261a54:
  .incbin "sound/direct_sound_samples/unk_08261a54.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08264088
DirectSoundWaveData_unk_08264088:
  .incbin "sound/direct_sound_samples/unk_08264088.bin"

@;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

  .balign 4, 0
.global DirectSoundWaveData_unk_0826602c
DirectSoundWaveData_unk_0826602c:
  .incbin "sound/direct_sound_samples/unk_0826602c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0826908c
DirectSoundWaveData_unk_0826908c:
  .incbin "sound/direct_sound_samples/unk_0826908c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082695cc
DirectSoundWaveData_unk_082695cc:
  .incbin "sound/direct_sound_samples/unk_082695cc.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0826b4f8
DirectSoundWaveData_unk_0826b4f8:
  .incbin "sound/direct_sound_samples/unk_0826b4f8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0826e5ec
DirectSoundWaveData_unk_0826e5ec:
  .incbin "sound/direct_sound_samples/unk_0826e5ec.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08271668
DirectSoundWaveData_unk_08271668:
  .incbin "sound/direct_sound_samples/unk_08271668.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082732e4
DirectSoundWaveData_unk_082732e4:
  .incbin "sound/direct_sound_samples/unk_082732e4.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08276988
DirectSoundWaveData_unk_08276988:
  .incbin "sound/direct_sound_samples/unk_08276988.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08278b44
DirectSoundWaveData_unk_08278b44:
  .incbin "sound/direct_sound_samples/unk_08278b44.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082795d8
DirectSoundWaveData_unk_082795d8:
  .incbin "sound/direct_sound_samples/unk_082795d8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0827aa18
DirectSoundWaveData_unk_0827aa18:
  .incbin "sound/direct_sound_samples/unk_0827aa18.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0827bf30
DirectSoundWaveData_unk_0827bf30:
  .incbin "sound/direct_sound_samples/unk_0827bf30.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0827dd14
DirectSoundWaveData_unk_0827dd14:
  .incbin "sound/direct_sound_samples/unk_0827dd14.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0827f8ac
DirectSoundWaveData_unk_0827f8ac:
  .incbin "sound/direct_sound_samples/unk_0827f8ac.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0828220c
DirectSoundWaveData_unk_0828220c:
  .incbin "sound/direct_sound_samples/unk_0828220c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08283898
DirectSoundWaveData_unk_08283898:
  .incbin "sound/direct_sound_samples/unk_08283898.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08285014
DirectSoundWaveData_unk_08285014:
  .incbin "sound/direct_sound_samples/unk_08285014.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08286ec8
DirectSoundWaveData_unk_08286ec8:
  .incbin "sound/direct_sound_samples/unk_08286ec8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082890b8
DirectSoundWaveData_unk_082890b8:
  .incbin "sound/direct_sound_samples/unk_082890b8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0828bc88
DirectSoundWaveData_unk_0828bc88:
  .incbin "sound/direct_sound_samples/unk_0828bc88.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0828cde0
DirectSoundWaveData_unk_0828cde0:
  .incbin "sound/direct_sound_samples/unk_0828cde0.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0828e6d8
DirectSoundWaveData_unk_0828e6d8:
  .incbin "sound/direct_sound_samples/unk_0828e6d8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08290124
DirectSoundWaveData_unk_08290124:
  .incbin "sound/direct_sound_samples/unk_08290124.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08290cbc
DirectSoundWaveData_unk_08290cbc:
  .incbin "sound/direct_sound_samples/unk_08290cbc.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08291b24
DirectSoundWaveData_unk_08291b24:
  .incbin "sound/direct_sound_samples/unk_08291b24.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08293e94
DirectSoundWaveData_unk_08293e94:
  .incbin "sound/direct_sound_samples/unk_08293e94.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0829706c
DirectSoundWaveData_unk_0829706c:
  .incbin "sound/direct_sound_samples/unk_0829706c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0829d180
DirectSoundWaveData_unk_0829d180:
  .incbin "sound/direct_sound_samples/unk_0829d180.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082a0a44
DirectSoundWaveData_unk_082a0a44:
  .incbin "sound/direct_sound_samples/unk_082a0a44.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082a2424
DirectSoundWaveData_unk_082a2424:
  .incbin "sound/direct_sound_samples/unk_082a2424.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082a4dd8
DirectSoundWaveData_unk_082a4dd8:
  .incbin "sound/direct_sound_samples/unk_082a4dd8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082a6f40
DirectSoundWaveData_unk_082a6f40:
  .incbin "sound/direct_sound_samples/unk_082a6f40.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082a7ef4
DirectSoundWaveData_unk_082a7ef4:
  .incbin "sound/direct_sound_samples/unk_082a7ef4.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082a8a6c
DirectSoundWaveData_unk_082a8a6c:
  .incbin "sound/direct_sound_samples/unk_082a8a6c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082ab314
DirectSoundWaveData_unk_082ab314:
  .incbin "sound/direct_sound_samples/unk_082ab314.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082ada38
DirectSoundWaveData_unk_082ada38:
  .incbin "sound/direct_sound_samples/unk_082ada38.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082aff20
DirectSoundWaveData_unk_082aff20:
  .incbin "sound/direct_sound_samples/unk_082aff20.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082b24ac
DirectSoundWaveData_unk_082b24ac:
  .incbin "sound/direct_sound_samples/unk_082b24ac.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082b4314
DirectSoundWaveData_unk_082b4314:
  .incbin "sound/direct_sound_samples/unk_082b4314.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082b7874
DirectSoundWaveData_unk_082b7874:
  .incbin "sound/direct_sound_samples/unk_082b7874.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082b94c4
DirectSoundWaveData_unk_082b94c4:
  .incbin "sound/direct_sound_samples/unk_082b94c4.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082ba04c
DirectSoundWaveData_unk_082ba04c:
  .incbin "sound/direct_sound_samples/unk_082ba04c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082badcc
DirectSoundWaveData_unk_082badcc:
  .incbin "sound/direct_sound_samples/unk_082badcc.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082bbf8c
DirectSoundWaveData_unk_082bbf8c:
  .incbin "sound/direct_sound_samples/unk_082bbf8c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082bd6f8
DirectSoundWaveData_unk_082bd6f8:
  .incbin "sound/direct_sound_samples/unk_082bd6f8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082be9fc
DirectSoundWaveData_unk_082be9fc:
  .incbin "sound/direct_sound_samples/unk_082be9fc.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082c0e1c
DirectSoundWaveData_unk_082c0e1c:
  .incbin "sound/direct_sound_samples/unk_082c0e1c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082c2494
DirectSoundWaveData_unk_082c2494:
  .incbin "sound/direct_sound_samples/unk_082c2494.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082c5820
DirectSoundWaveData_unk_082c5820:
  .incbin "sound/direct_sound_samples/unk_082c5820.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082c8c64
DirectSoundWaveData_unk_082c8c64:
  .incbin "sound/direct_sound_samples/unk_082c8c64.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082c8dbc
DirectSoundWaveData_unk_082c8dbc:
  .incbin "sound/direct_sound_samples/unk_082c8dbc.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082ca484
DirectSoundWaveData_unk_082ca484:
  .incbin "sound/direct_sound_samples/unk_082ca484.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082cc434
DirectSoundWaveData_unk_082cc434:
  .incbin "sound/direct_sound_samples/unk_082cc434.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082ce0c4
DirectSoundWaveData_unk_082ce0c4:
  .incbin "sound/direct_sound_samples/unk_082ce0c4.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082d03e4
DirectSoundWaveData_unk_082d03e4:
  .incbin "sound/direct_sound_samples/unk_082d03e4.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082d33d4
DirectSoundWaveData_unk_082d33d4:
  .incbin "sound/direct_sound_samples/unk_082d33d4.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082d6444
DirectSoundWaveData_unk_082d6444:
  .incbin "sound/direct_sound_samples/unk_082d6444.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082d7b98
DirectSoundWaveData_unk_082d7b98:
  .incbin "sound/direct_sound_samples/unk_082d7b98.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082d9060
DirectSoundWaveData_unk_082d9060:
  .incbin "sound/direct_sound_samples/unk_082d9060.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082d9ee8
DirectSoundWaveData_unk_082d9ee8:
  .incbin "sound/direct_sound_samples/unk_082d9ee8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082db714
DirectSoundWaveData_unk_082db714:
  .incbin "sound/direct_sound_samples/unk_082db714.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082dcee0
DirectSoundWaveData_unk_082dcee0:
  .incbin "sound/direct_sound_samples/unk_082dcee0.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082ded00
DirectSoundWaveData_unk_082ded00:
  .incbin "sound/direct_sound_samples/unk_082ded00.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082e0dfc
DirectSoundWaveData_unk_082e0dfc:
  .incbin "sound/direct_sound_samples/unk_082e0dfc.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082e3a38
DirectSoundWaveData_unk_082e3a38:
  .incbin "sound/direct_sound_samples/unk_082e3a38.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082e5ddc
DirectSoundWaveData_unk_082e5ddc:
  .incbin "sound/direct_sound_samples/unk_082e5ddc.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082e682c
DirectSoundWaveData_unk_082e682c:
  .incbin "sound/direct_sound_samples/unk_082e682c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082e8da0
DirectSoundWaveData_unk_082e8da0:
  .incbin "sound/direct_sound_samples/unk_082e8da0.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082e97d0
DirectSoundWaveData_unk_082e97d0:
  .incbin "sound/direct_sound_samples/unk_082e97d0.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082eaa24
DirectSoundWaveData_unk_082eaa24:
  .incbin "sound/direct_sound_samples/unk_082eaa24.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082eba40
DirectSoundWaveData_unk_082eba40:
  .incbin "sound/direct_sound_samples/unk_082eba40.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082ed794
DirectSoundWaveData_unk_082ed794:
  .incbin "sound/direct_sound_samples/unk_082ed794.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082ee0c4
DirectSoundWaveData_unk_082ee0c4:
  .incbin "sound/direct_sound_samples/unk_082ee0c4.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082f082c
DirectSoundWaveData_unk_082f082c:
  .incbin "sound/direct_sound_samples/unk_082f082c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082f21d8
DirectSoundWaveData_unk_082f21d8:
  .incbin "sound/direct_sound_samples/unk_082f21d8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082f41a8
DirectSoundWaveData_unk_082f41a8:
  .incbin "sound/direct_sound_samples/unk_082f41a8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082f50c0
DirectSoundWaveData_unk_082f50c0:
  .incbin "sound/direct_sound_samples/unk_082f50c0.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082f73dc
DirectSoundWaveData_unk_082f73dc:
  .incbin "sound/direct_sound_samples/unk_082f73dc.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082f8634
DirectSoundWaveData_unk_082f8634:
  .incbin "sound/direct_sound_samples/unk_082f8634.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082f9214
DirectSoundWaveData_unk_082f9214:
  .incbin "sound/direct_sound_samples/unk_082f9214.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082fa094
DirectSoundWaveData_unk_082fa094:
  .incbin "sound/direct_sound_samples/unk_082fa094.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082fc464
DirectSoundWaveData_unk_082fc464:
  .incbin "sound/direct_sound_samples/unk_082fc464.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082fe94c
DirectSoundWaveData_unk_082fe94c:
  .incbin "sound/direct_sound_samples/unk_082fe94c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_082ff658
DirectSoundWaveData_unk_082ff658:
  .incbin "sound/direct_sound_samples/unk_082ff658.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0830017c
DirectSoundWaveData_unk_0830017c:
  .incbin "sound/direct_sound_samples/unk_0830017c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_083010a4
DirectSoundWaveData_unk_083010a4:
  .incbin "sound/direct_sound_samples/unk_083010a4.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08302ba8
DirectSoundWaveData_unk_08302ba8:
  .incbin "sound/direct_sound_samples/unk_08302ba8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08304d4c
DirectSoundWaveData_unk_08304d4c:
  .incbin "sound/direct_sound_samples/unk_08304d4c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08305e30
DirectSoundWaveData_unk_08305e30:
  .incbin "sound/direct_sound_samples/unk_08305e30.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_083077d8
DirectSoundWaveData_unk_083077d8:
  .incbin "sound/direct_sound_samples/unk_083077d8.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08309a84
DirectSoundWaveData_unk_08309a84:
  .incbin "sound/direct_sound_samples/unk_08309a84.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0830a800
DirectSoundWaveData_unk_0830a800:
  .incbin "sound/direct_sound_samples/unk_0830a800.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08312b68
DirectSoundWaveData_unk_08312b68:
  .incbin "sound/direct_sound_samples/unk_08312b68.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08314f1c
DirectSoundWaveData_unk_08314f1c:
  .incbin "sound/direct_sound_samples/unk_08314f1c.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08316548
DirectSoundWaveData_unk_08316548:
  .incbin "sound/direct_sound_samples/unk_08316548.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08318644
DirectSoundWaveData_unk_08318644:
  .incbin "sound/direct_sound_samples/unk_08318644.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08319f40
DirectSoundWaveData_unk_08319f40:
  .incbin "sound/direct_sound_samples/unk_08319f40.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0831c184
DirectSoundWaveData_unk_0831c184:
  .incbin "sound/direct_sound_samples/unk_0831c184.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0831d4fc
DirectSoundWaveData_unk_0831d4fc:
  .incbin "sound/direct_sound_samples/unk_0831d4fc.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_0831e9dc
DirectSoundWaveData_unk_0831e9dc:
  .incbin "sound/direct_sound_samples/unk_0831e9dc.bin"

  .balign 4, 0
.global DirectSoundWaveData_unk_08322e60
DirectSoundWaveData_unk_08322e60:
  .incbin "sound/direct_sound_samples/unk_08322e60.bin"

@;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
