#ifndef GUARD_RMZ3_CONST_CYBERELF_H
#define GUARD_RMZ3_CONST_CYBERELF_H

#define ELF_MARTINA 0    // Priestess
#define ELF_MILVY 1      // NurseA
#define ELF_ELPHY 2      // NurseA
#define ELF_SYLPHY 3     // NurseA
#define ELF_RILPHY 4     // NurseA
#define ELF_ARTAN 5      // NurseB
#define ELF_ZICTAN 6     // NurseB
#define ELF_MOTT 7       // NurseD
#define ELF_DOTT 8       // NurseD
#define ELF_CURIPH 9     // NurseA
#define ELF_LURIPH 10    // NurseA
#define ELF_SURIPH 11    // NurseA
#define ELF_TIRIPH 12    // NurseA
#define ELF_YURIPH 13    // NurseA
#define ELF_BERIPH 14    // NurseA
#define ELF_WILIPH 15    // NurseA
#define ELF_CYLIPH 16    // NurseA
#define ELF_SNOQ 17      // NurseC
#define ELF_MATHIQ 18    // NurseC
#define ELF_MIYAQ 19     // NurseC
#define ELF_AJIQ 20      // NurseC
#define ELF_DOBUQ 21     // NurseC
#define ELF_MULAQ 22     // NurseC
#define ELF_MAILLA 23    // NurseB
#define ELF_MIULLA 24    // NurseB
#define ELF_CLOPPE 25    // NurseE
#define ELF_SLOPPE 26    // NurseE
#define ELF_PUTITE 27    // Slime
#define ELF_BALETTE 28   // Cheetah
#define ELF_MAYA 29      // Monkey
#define ELF_KWAPPA 30    // Frog
#define ELF_GAMBUL 31    // Cow
#define ELF_BIRAID 32    // Bird
#define ELF_BIRLEAF 33   // Bird
#define ELF_PITAPAH 34   // SeaOtter
#define ELF_PITAPUH 35   // SeaOtter
#define ELF_BEETACK 36   // Bee
#define ELF_BEENIPE 37   // Bee
#define ELF_ARCHIM 38    // Arch
#define ELF_ARCHIL 39    // Arch
#define ELF_BYSE 40      // Item
#define ELF_DYLPHINA 41  // Item
#define ELF_LIZETUS 42   // Shinobi
#define ELF_COTTUS 43    // Shinobi
#define ELF_SHUTHAS 44   // Shinobi
#define ELF_MALTHAS 45   // Shinobi
#define ELF_ILETHAS 46   // Shinobi
#define ELF_ENETHAS 47   // Shinobi
#define ELF_BUSRAS 48    // Mikoshi
#define ELF_SABRAS 49    // Mikoshi
#define ELF_RODERAS 50   // Mikoshi
#define ELF_BOOMERAS 51  // Mikoshi
#define ELF_CLOKKLE 52   // Clock
#define ELF_METORAS 53   // Metall
#define ELF_METORIKA 54  // Metall
#define ELF_METORPH 55   // Metall
#define ELF_METELLA 56   // Metall
#define ELF_METEROM 57   // Metall
#define ELF_KYNITE 58    // Armor
#define ELF_SURNITE 59   // Armor
#define ELF_TENITE 60    // Armor
#define ELF_STOPALLA 61  // Time
#define ELF_STOPINA 62   // Time
#define ELF_STOPULE 63   // Time
#define ELF_STOPETA 64   // Time
#define ELF_STOPOSA 65   // Time
#define ELF_HANMARGA 66  // Giant
#define ELF_HANMARJI 67  // Giant
#define ELF_HANMARBO 68  // Giant
#define ELF_AINA 69      // Whistle
#define ELF_ACOOL 70     // Whistle
#define ELF_ACHOON 71    // Whistle
#define ELF_ANATER 72    // Whistle
#define ELF_AWARNE 73    // Whistle
#define ELF_NONE 255

#endif  // GUARD_RMZ3_CONST_CYBERELF_H
