#ifndef GUARD_RMZ3_CONST_ENEMY_H
#define GUARD_RMZ3_CONST_ENEMY_H

#define ENEMY_P_GUARDIAN 0
#define ENEMY_P_HUNTER 1
#define ENEMY_MEGAMILPA_NODE 2
#define ENEMY_SHOTCOUNTER 3
#define ENEMY_BATRING 4
#define ENEMY_PILLER_CANNON 5
#define ENEMY_GRAND_CANNON 6
#define ENEMY_SHRIMPORIN 7
#define ENEMY_OMEGA_WHITE_HAND 8
#define ENEMY_FLOPPER 9
#define ENEMY_LAMPLORT 10
#define ENEMY_GYRO_CANNON 11
#define ENEMY_LEMMINGLES_NEST 12
#define ENEMY_LEMMINGLES 13
#define ENEMY_14 14
#define ENEMY_SHARKSEAL_X 15
#define ENEMY_VOLCANO_BOMB 16
#define ENEMY_CARRY_ARM 17
#define ENEMY_P_AQUA 18
#define ENEMY_CHILDRE_OBJ 19
#define ENEMY_SNAKECORD 20
#define ENEMY_HAMMER 21
#define ENEMY_PURPLE_NERPLE 22
#define ENEMY_WORMER_ROCK_DRONE 23
#define ENEMY_VOLCAIRE 24
#define ENEMY_TILE_CANNON 25
#define ENEMY_SHELLUNO 26
#define ENEMY_DEATHTANZ_ROCK 27
#define ENEMY_HEAVY_CANNON_BALL 28
#define ENEMY_WORMER_SNOW_BALL 29
#define ENEMY_BEETANK 30
#define ENEMY_SWORDY 31
#define ENEMY_PUFFY 32
#define ENEMY_CROSSBYNE 33
#define ENEMY_BURNABLE_WOOD 34
#define ENEMY_MELLNET 35
#define ENEMY_HELL_BOUNCER 36
#define ENEMY_P_ZOMBIE 37
#define ENEMY_P_AQUA_MOD_OBJ 38

// (ENEMY_GRAND_CANNON->s).work[0]
#define GRAND_CANNON_TURRET 0   // 筒(Turret)
#define GRAND_CANNON_BATTERY 1  // 砲台(Child)

#endif  // GUARD_RMZ3_CONST_ENEMY_H
