#ifndef GUARD_RMZ3_CONST_ENEMY_H
#define GUARD_RMZ3_CONST_ENEMY_H

#define ENEMY_P_GUARDIAN 0
#define ENEMY_P_HUNTER 1
#define ENEMY_MEGAMILPA_NODE 2
#define ENEMY_SHOTCOUNTER 3
#define ENEMY_BATRING 4
#define ENEMY_PILLER_CANNON 5
#define ENEMY_GRAND_CANNON 6
#define ENEMY_SHRIMPORIN 7
#define ENEMY_OMEGA_WHITE_HAND 8
#define ENEMY_FLOPPER 9
#define ENEMY_LAMPLORT 10
#define ENEMY_GYRO_CANNON 11
#define ENEMY_LEMMINGLES_NEST 12
#define ENEMY_LEMMINGLES 13
#define ENEMY_TOP_GABYOALL 14
#define ENEMY_SHARKSEAL_X 15
#define ENEMY_VOLCANO_BOMB 16
#define ENEMY_CARRY_ARM 17
#define ENEMY_P_AQUA 18
#define ENEMY_CHILDRE_OBJ 19
#define ENEMY_SNAKECORD 20
#define ENEMY_HAMMER 21
#define ENEMY_PURPLE_NERPLE 22
#define ENEMY_WORMER_ROCK_DRONE 23
#define ENEMY_VOLCAIRE 24
#define ENEMY_TILE_CANNON 25
#define ENEMY_SHELLUNO 26
#define ENEMY_DEATHTANZ_ROCK 27
#define ENEMY_HEAVY_CANNON_BALL 28
#define ENEMY_WORMER_SNOW_BALL 29
#define ENEMY_BEETANK 30
#define ENEMY_SWORDY 31
#define ENEMY_PUFFY 32
#define ENEMY_CROSSBYNE 33
#define ENEMY_BURNABLE_WOOD 34
#define ENEMY_MELLNET 35
#define ENEMY_HELL_BOUNCER 36
#define ENEMY_P_ZOMBIE 37
#define ENEMY_P_AQUA_MOD_OBJ 38
#define ENEMY_GLACIERLE_ARM 39
#define ENEMY_OMEGA_GOLD_HAND 40
#define ENEMY_EYE_CANNON 41
#define ENEMY_42 42
#define ENEMY_CAPSULE_CANNON 43
#define ENEMY_P_BOMBER 44
#define ENEMY_HANUMACHINE_OBJ 45
#define ENEMY_GALLISNI 46
#define ENEMY_MOTHJIRO 47
#define ENEMY_METTAUR_SWIM 48
#define ENEMY_P_BASE 49
#define ENEMY_HANUMACHINE_NECRO 50
#define ENEMY_CARRYBEE_G 51
#define ENEMY_OZ_ROCK 52
#define ENEMY_OMEGA_GOLD_SWORD 53
#define ENEMY_GENERATOR_CANNON 54
#define ENEMY_DEATHLOCK 55
#define ENEMY_CLAVEKER 56
#define ENEMY_SEIMERAN 57
#define ENEMY_PETATRIA 58
#define ENEMY_59 59
#define ENEMY_60 60
#define ENEMY_61 61
#define ENEMY_SHOTLOID 62
#define ENEMY_63 63
#define ENEMY_P_FIST 64
#define ENEMY_SHELLCRAWLER 65
#define ENEMY_CANNON_HOPPER 66
#define ENEMY_CATTATANK 67
#define ENEMY_68 68
#define ENEMY_AZTEC_FALCON 69  // Harpuia minigame
#define ENEMY_70 70
#define ENEMY_71 71
#define ENEMY_72 72

#define ENEMY_COUNT (ENEMY_72 + 1)

// (ENEMY_GRAND_CANNON->s).work[0]
#define GRAND_CANNON_TURRET 0   // 筒(Turret)
#define GRAND_CANNON_BATTERY 1  // 砲台(Child)

#endif  // GUARD_RMZ3_CONST_ENEMY_H
