#ifndef GUARD_RMZ3_CONST_MINIGAME_H
#define GUARD_RMZ3_CONST_MINIGAME_H

#define MINIGAME_ZERO 0
#define MINIGAME_CIEL 1
#define MINIGAME_COPY_X 2
#define MINIGAME_HARPUIA 3
#define MINIGAME_FEFNIR 4
#define MINIGAME_LEVIATHAN 5
#define MINIGAME_PHANTOM 6

#endif  // GUARD_RMZ3_CONST_MINIGAME_H
