#ifndef GUARD_RMZ3_CONST_SIZE_H
#define GUARD_RMZ3_CONST_SIZE_H

#define SLOT_4BPP 16

#define SAVE_SLOT 5
#define SAVE_SLOT_SIZE 592

#define MUSIC_PLAYER_LENGTH 15
#define CYBERELF_LENGTH 74

#define TASK_LENGTH 128

#define SAVE_DATA_NUM 5
#define SLOT_SYSTEM SAVE_DATA_NUM
#define SLOT_SIZE (2730 + 16)

#endif  // GUARD_RMZ3_CONST_SIZE_H
