    .balign 4
    .section .rodata

gStage0_Terrain: @ 0x0863c654
    .incbin "data/stage/stage0/metatile.bin"
    .incbin "data/stage/stage0/metatile_attr.bin"
    .incbin "data/stage/stage0/screen.bin"

gSpaceCraft_Terrain: @ 0x0863c7a8
    .incbin "data/stage/spacecraft/metatile.bin"
    .incbin "data/stage/spacecraft/metatile_attr.bin"
    .incbin "data/stage/spacecraft/screen.bin"

gVolcano_Terrain: @ 0x08644cb4
    .incbin "data/stage/volcano/metatile.bin"
    .incbin "data/stage/volcano/metatile_attr.bin"
    .incbin "data/stage/volcano/screen.bin"

gOcean_Terrain: @ 0x08653e30
    .incbin "data/stage/ocean/metatile.bin"
    .incbin "data/stage/ocean/metatile_attr.bin"
    .incbin "data/stage/ocean/screen.bin"

gRepairFactory_Terrain: @ 0x08662534
    .incbin "data/stage/repair_factory/metatile.bin"
    .incbin "data/stage/repair_factory/metatile_attr.bin"
    .incbin "data/stage/repair_factory/screen.bin"

gOldLifeSpace_Terrain: @ 0x0866f0cc
    .incbin "data/stage/old_residential/metatile.bin"
    .incbin "data/stage/old_residential/metatile_attr.bin"
    .incbin "data/stage/old_residential/screen.bin"

gMissileFactory_Terrain: @ 0x086807c8
    .incbin "data/stage/missile_factory/metatile.bin"
    .incbin "data/stage/missile_factory/metatile_attr.bin"
    .incbin "data/stage/missile_factory/screen.bin"

gTwilightDesert_Terrain: @ 0x08690ec0
    .incbin "data/stage/twilight_desert/metatile.bin"
    .incbin "data/stage/twilight_desert/metatile_attr.bin"
    .incbin "data/stage/twilight_desert/screen.bin"

gAnatreForest_Terrain: @ 0x08698d8c
    .incbin "data/stage/anatre_forest/metatile.bin"
    .incbin "data/stage/anatre_forest/metatile_attr.bin"
    .incbin "data/stage/anatre_forest/screen.bin"

gFrostBaseLine_Terrain: @ 0x086a323c
    .incbin "data/stage/frostline_ice_base/metatile.bin"
    .incbin "data/stage/frostline_ice_base/metatile_attr.bin"
    .incbin "data/stage/frostline_ice_base/screen.bin"

gAreaX2_Terrain: @ 0x086ae90c
    .incbin "data/stage/area_x2/metatile.bin"
    .incbin "data/stage/area_x2/metatile_attr.bin"
    .incbin "data/stage/area_x2/screen.bin"

gEnergyFacility_Terrain: @ 0x086b6ff8
    .incbin "data/stage/energy_facility/metatile.bin"
    .incbin "data/stage/energy_facility/metatile_attr.bin"
    .incbin "data/stage/energy_facility/screen.bin"

gSnowyPlains_Terrain: @ 0x086c3e60
    .incbin "data/stage/snowy_plains/metatile.bin"
    .incbin "data/stage/snowy_plains/metatile_attr.bin"
    .incbin "data/stage/snowy_plains/screen.bin"

gSunkenLibrary_Terrain: @ 0x086d2910
    .incbin "data/stage/sunken_library/metatile.bin"
    .incbin "data/stage/sunken_library/metatile_attr.bin"
    .incbin "data/stage/sunken_library/screen.bin"

gGiantElevator_Terrain: @ 0x086db010
    .incbin "data/stage/giant_elevator/metatile.bin"
    .incbin "data/stage/giant_elevator/metatile_attr.bin"
    .incbin "data/stage/giant_elevator/screen.bin"

gSubArcadia_Terrain: @ 0x086e2a2c
    .incbin "data/stage/sub_arcadia/metatile.bin"
    .incbin "data/stage/sub_arcadia/metatile_attr.bin"
    .incbin "data/stage/sub_arcadia/screen.bin"

gWeilLabo_Terrain: @ 0x086ee6b0
    .incbin "data/stage/weil_labo/metatile.bin"
    .incbin "data/stage/weil_labo/metatile_attr.bin"
    .incbin "data/stage/weil_labo/screen.bin"

gResistanceBase_Terrain: @ 0x086f9fec
    .incbin "data/stage/resistance_base/metatile.bin"
    .incbin "data/stage/resistance_base/metatile_attr.bin"
    .incbin "data/stage/resistance_base/screen.bin"

