#ifndef GUARD_RMZ3_CONST_PLAYER_H
#define GUARD_RMZ3_CONST_PLAYER_H

// Player.id
#define PLAYER_ZERO 0
#define PLAYER_MINIGAME_FEFNIR 1
#define PLAYER_MINIGAME_PHANTOM 2
#define PLAYER_MINIGAME_HARPUIA 3
#define PLAYER_MINIGAME_COPY_X 4
#define PLAYER_MINIGAME_LEVIATHAN 5
#define PLAYER_MINIGAME_ZERO 6
#define PLAYER_ENTITY_COUNT 7

#define ZERO 0

#endif  // GUARD_RMZ3_CONST_PLAYER_H
