#!/usr/bin/env -S deno run --allow-read

import { Command } from '@cliffy/command';
import { addr, getRGBg, getU16, getU32, getU8, ROM_PATH, toHex } from '../common/index.ts';

const COUNTS = 280;

const LABEL = 'PlttAnimData';

const ANIMCND_MACRO = `
.macro ac_data target duration
\t.byte \\target, \\duration
.endm

.macro ac_goto dst
\t.byte \\dst, 254
.endm

.macro ac_end
\t.byte 0, 255
.endm`;

const align = (n: number, val: number = 0): string => `.balign ${n}, ${val}`;

const main = async () => {
  const { args } = await new Command()
    .name('palanim.ts')
    .version('1.0.0')
    .description('PaletteAnimation dumper')
    .argument('<data:number>', 'gPlttAnimDataOffsets')
    .argument('<cmd:number>', 'gPlttAnimScriptTable')
    .usage('0x085b5cd0 0x085be764')
    .parse(Deno.args);

  const rom = new DataView(Deno.readFileSync(ROM_PATH).buffer);
  const offsets: addr = Number(args[0]);
  const cmds: addr = Number(args[1]);
  const length = getU32(rom, offsets) / 4; // BZ3J: 0x460 -> 280
  if (length !== COUNTS) {
    console.error(`Expected length: ${COUNTS}, but got: ${length}`);
    Deno.exit(1);
  }

  const comment = `@ generated by tools/dumper/palanim.ts 0x${toHex(offsets, 8)} 0x${toHex(cmds, 8)}`;
  const includes = [
    `#include "constants/rgb.h"`,
  ];
  const macros = [
    `.balign 4`,
    `.section .rodata`,
    `.set BGP, 16`,
    ANIMCND_MACRO,
  ];
  let result = comment + '\n\n' + includes.join('\n') + '\n\n' + macros.join('\n') + '\n\n';

  {
    const addrs: addr[] = new Array<addr>(COUNTS).fill(-1);
    for (let i = 0; i < COUNTS; i++) {
      const ptr: addr = offsets + (i * 4); // shitty self rel ptr
      const offset = getU32(rom, ptr);
      const addr = ptr + offset; // e.g. 0x085ba244
      addrs[i] = addr;
    }

    // gPlttAnimDataOffsets
    let tbl = `.global gPlttAnimDataOffsets\ngPlttAnimDataOffsets: @ 0x${toHex(offsets, 8)}`;
    for (let i = 0; i < COUNTS; i++) {
      const idx = addrs.indexOf(addrs[i]);
      const val = `${LABEL}${String(idx).padStart(3, '0')}-.`;
      tbl += (i % 10 === 0) ? `\n\t.4byte ${val}` : `, ${val}`;
    }

    let body = '';
    for (let i = 0; i < COUNTS; i++) {
      const idx = addrs.indexOf(addrs[i]); // すでに定義済みの PlttAnimData なら、再定義しないようにする
      if (idx === i) body += parsePlttAnimData(rom, i, addrs[i]) + '\n';
    }
    result += tbl + '\n\n' + body;
  }

  {
    const addrs: addr[] = new Array<addr>(COUNTS).fill(-1);
    for (let i = 0; i < COUNTS; i++) {
      addrs[i] = getU32(rom, cmds + (i * 4)); // normal ptr;
    }

    // gPlttAnimScriptTable
    const label = 'gPlttAnimScript';
    let tbl = `.global gPlttAnimScriptTable\ngPlttAnimScriptTable: @ 0x${toHex(cmds, 8)}`;
    for (let i = 0; i < COUNTS; i++) {
      const idx = addrs.indexOf(addrs[i]);
      const val = `${label}${String(idx).padStart(3, '0')}`;
      tbl += (i % 10 === 0) ? `\n\t.4byte ${val}` : `, ${val}`;
    }

    let body = '';
    for (let i = 0; i < COUNTS; i++) {
      const idx = addrs.indexOf(addrs[i]); // すでに定義済みの AnimScript なら、再定義しないようにする
      if (idx === i) body += parsePlttAnimScript(rom, i, addrs[i]);
    }
    result += tbl + '\n\n' + body + `\n${align(4)}\n`;
  }
  console.log(result);
};

const parsePlttAnimData = (rom: DataView, idx: number, addr: addr): string => {
  const frames = getU8(rom, addr);
  const start = getU8(rom, addr + 1);
  const [startBGP, startColorIdx] = [start >> 4, start & 0xF];
  const end = getU8(rom, addr + 2);
  const [endBGP, endColorIdx] = [end >> 4, end & 0xF];
  let result = `${align(4)}\n${LABEL}${String(idx).padStart(3, '0')}: @ 0x${toHex(addr, 8)}
\t.byte ${frames}, (${startBGP}*BGP + ${startColorIdx}), (${endBGP}*BGP + ${endColorIdx}) @ frames, start, end\n\t${align(4)}\n`;

  const colorlen = end - start + 1; // 4 + ((colorlen*2) * frames) が全体のサイズ
  for (let i = 0; i < frames; i++) {
    const pltt = addr + 4 + ((colorlen * 2) * i); // rgb555[colorlen]
    const colors: string[] = new Array<string>(colorlen).fill('0');
    for (let j = 0; j < colorlen; j++) {
      colors[j] = getRGBg(getU16(rom, pltt + (j * 2)));
    }
    result += `\t\t.2byte ${colors.join(', ')} @ frame: ${String(i).padStart(2)}, addr: 0x${toHex(pltt, 8)}\n`;
  }
  return result;
};

const parsePlttAnimScript = (rom: DataView, idx: number, addr: addr): string => {
  const script: addr = getU32(rom, addr);
  if (script !== addr + 4) { // PaletteAnimation は AnimScript を1つしか持たない
    console.error(`Expected script ptr: 0x${toHex(addr + 4, 8)}, but got: 0x${toHex(script, 8)}`);
    Deno.exit(1);
  }
  const label = `PlttAnimScript${String(idx).padStart(3, '0')}`;
  let result = `\n${align(4)}\ng${label}: @ 0x${toHex(script, 8)}
\t.4byte ${label}_0
\t${label}_0:\n`;
  for (let j = 0;; j++) {
    const param: number = getU8(rom, script + (j * 2));
    const op: number = getU8(rom, script + (j * 2) + 1);
    if (op === 0xFF) { // terminate
      result += `\t\tac_end\n`;
      break;
    } else if (op === 0xFE) { // infiniteloop
      // result += `\t\t.byte ${param}, ${op} @ infiniteloop\n`;
      result += `\t\tac_goto ${param}\n`;
      break;
    } else {
      result += `\t\tac_data ${param}, ${op} @ ${j}\n`;
    }
    if (j === 256) { // sentinel
      console.error(`Script${idx} (in: 0x${toHex(script, 8)}) too long, exceeded 256 entries at index ${j}`);
      Deno.exit(1);
    }
  }
  return result;
};

main();
