#!/usr/bin/env -S deno run --allow-read

import { Command } from '@cliffy/command';
import { SEPARATOR } from '../common/index.ts';
import { basename } from '@std/path';

/**
 * metasprite.json から アセンブリファイル を生成するスクリプト (metasprite.json のフォーマット後述の型定義を参照)
 * 実行すると次のようなファイルが生成されます
 * 生成したファイルは .inc として、 sprites/dynamic/anim.s もしくは sprites/static/anim.s に使用されます
 *
 * .section .rodata
 * .balign 4, 0
 * .global gXXXX
 * gXXXX:
 *   @ ヘッダ列 (include/motion.h の MetaspriteHeader)
 *     @ metasprite.json の data[0] のヘッダ
 *       .2byte ofs                 @ $+ofs = Subsprite[]のアドレス
 *       .byte  subspriteCount      @ メタスプライトを構成するスプライト数
 *       .byte  sheetIdx            @ 使用するテクスチャ
 *     @ metasprite.json の data[1] のヘッダ
 *       .2byte ofs                 @ $+ofs = Subsprite[]のアドレス
 *       .byte  subspriteCount      @ メタスプライトを構成するスプライト数
 *       .byte  sheetIdx            @ 使用するテクスチャ
 *     @ 以下略
 *       ...
 *  @ Subsprite列 (include/motion.h の Subsprite)
 *    @ 0
 *      .2byte attr
 *      .byte  x, y
 *    @ 1
 *      .2byte attr
 *      .byte  x, y
 *    @ 以下略
 *      ...
 */

const SUPRITE_SIZE: [number, number][] = [
  [8, 8],
  [16, 16],
  [32, 32],
  [64, 64],

  [16, 8],
  [32, 8],
  [32, 16],
  [64, 32],

  [8, 16],
  [8, 32],
  [16, 32],
  [32, 64],
];

// metasprite.json の型定義
// TODO: metasprite.json は メタスプライト　を複数定義しているので metasprite.json という名前は適切でないかも
type JsonData = {
  label?: string;
  data: Metasprite[];
};

// 1枚のメタスプライト
type Metasprite = {
  sheetIdx: number; // テクスチャ (sheet/*.png) が複数ある場合にどれを使うかを指定する, テクスチャが 1枚(sheet.png) だけの場合は sheetIdx=0 としておく
  subsprites: Subsprite[]; // 構成するスプライト群
};

// メタスプライトを構成するGBAスプライト (OAMそのままのフォーマットではないことに注意)
type Subsprite = {
  tileNum: number;
  xflip?: boolean;
  yflip?: boolean;
  size: [number, number];
  x: number;
  y: number;
};

// metasprite.json (メタスプライトをGBAのスプライトからどう組み立てるかを記述したファイル) から metasprite.inc (アセンブリファイル) を生成するスクリプト
// 結果は標準出力に出るので、ファイルに保存したい場合は、リダイレクトしてくださって？
// e.g. ./tools/dev/metasprite.ts sprites/dynamic/zero/dash/metasprite.json > tmp/metasprite.inc
const main = async () => {
  const toolname = basename(import.meta.filename || '');
  if (!toolname) {
    console.error('Error: Could not determine tool name from import.meta.filename');
    Deno.exit(1);
  }

  const { args, options } = await new Command()
    .name('metasprite.ts')
    .version('1.0.0')
    .description('metasprite.json (メタスプライトをGBAのスプライトからどう組み立てるかを記述したファイル) から metasprite.inc (アセンブリファイル) を生成するスクリプト')
    .argument('<json:string>', 'metasprite.json のファイルパス')
    .option('--verbose', 'verbose')
    .option('-l, --label=[val:string]', 'Force label', { default: '' })
    .usage('sprites/dynamic/zero/dash/metasprite.json')
    .parse(Deno.args);

  const source = args[0];
  const json = JSON.parse(Deno.readTextFileSync(source)) as JsonData;
  const metasprites = json.data;
  if (options.verbose) {
    console.error(json); // stderr
  }

  const sizes = metasprites.map((metasprite) => (metasprite.subsprites.length * 4));

  const headers: string[] = [];
  for (let i = 0; i < metasprites.length; i++) {
    const metasprite = metasprites[i];
    let ofs = 4 * (metasprites.length - i) + (4 * i);
    if (i > 0) {
      ofs += sum(sizes.slice(0, i));
    }
    const header = `\t.2byte ${ofs}\n\t.byte ${metasprite.subsprites.length}, ${metasprite.sheetIdx} @ OAM sprites count, sheet/*.png`;
    headers.push(header);
  }

  let result = `@ Generated by the tools/dev/${toolname}. DO NOT EDIT!\n@ source: ${source}\n\n`;

  /**
   * .section .rodata
   * .balign 4, 0
   * .global [label]
   * [label]:
   */
  const label = options.label || json.label;
  result += `.section .rodata\n.balign 4, 0\n\n.global ${label}\n${label}:\n`;

  /**
   * .2byte 32
   * .byte 2, 0
   * .2byte 40
   * .byte 3, 0
   * ...
   */
  result += headers.join('\n') + `\n\t${SEPARATOR}\n`;

  metasprites.forEach((metasprite) => {
    metasprite.subsprites.forEach((subsprite) => {
      let u16 = subsprite.tileNum;
      if (subsprite.xflip) u16 |= 1 << 10;
      if (subsprite.yflip) u16 |= 1 << 11;
      u16 |= SUPRITE_SIZE.findIndex((size) => size[0] == subsprite.size[0] && size[1] == subsprite.size[1]) << 12;

      const x = subsprite.x >= 0 ? subsprite.x : 0x100 + subsprite.x;
      const y = subsprite.y >= 0 ? subsprite.y : 0x100 + subsprite.y;

      // struct Subsprite
      result += `\t.2byte 0x${u16.toString(16)}\n\t.byte ${x}, ${y}\n`;
    });
  });

  console.log(result);
};

const sum = (numbers: number[]) => {
  return numbers.reduce((accumulator, current) => accumulator + current, 0);
};

main();
