#include "sound.h"

#include "global.h"

NON_MATCH void InitSound(void) {
#if MODERN
  m4aSoundInit();
  gSongCount = ARRAY_COUNT(gSongTable);
  SoundID1 = MUS_DUMMY;
  SoundID2 = MUS_DUMMY;
#else
  INCCODE("asm/wip/InitSound.inc");
#endif
}

void StopAllMusics(void) {
  m4aMPlayAllStop();
  SoundID1 = MUS_DUMMY;
  SoundID2 = MUS_DUMMY;
}

void _usrHBlankCallback(void) {
  if (SoundID1 != 0) {
    SoundID1--;
  } else {
    if (SoundID2 != 0) {
      m4aSongNumStart(SoundID2);
      SoundID2 = 0;
      SoundID1 = 8;
    }
  }
  m4aSoundMain();
}

void FUN_080044a0(void) {
  m4aSoundVSync();
  return;
}

// メニュー画面を開いた時など、BGMの音量を落とす
NON_MATCH void TurnDownBGM(void) {
#if MODERN
  u32 i;
  for (i = 0; i < MUSIC_PLAYER_LENGTH; i++) {
    m4aMPlayVolumeControl(gMPlayTable[i].info, 0xFFFF, 0x60);
  }
#else
  INCCODE("asm/wip/TurnDownBGM.inc");
#endif
}

// メニュー画面から戻った時に、BGMを通常音量に戻す
NON_MATCH void TurnUpBGM(void) {
#if MODERN
  u32 i;
  for (i = 0; i < MUSIC_PLAYER_LENGTH; i++) {
    m4aMPlayVolumeControl(gMPlayTable[i].info, 0xFFFF, 0x100);
  }
#else
  INCCODE("asm/wip/TurnUpBGM.inc");
#endif
}

void playBGM(SoundID n) {
  m4aSongNumStart(n);
  return;
}

void fadeoutBGM(SoundID n) {
  bool32 playing = _isSoundPlaying(n);
  if (playing) {
    m4aMPlayFadeOut(gMPlayTable[gSongTable[n].ms].info, 6);
  }
}

bool32 _isSoundPlaying(SoundID n) {
  const struct MusicPlayerInfo *p = gMPlayTable[gSongTable[n].ms].info;
  if (p->songHeader == gSongTable[n].header) {
    s32 status32 = p->status;
    u16 status16 = (u16)p->status;
    if ((status16 != 0) && (status32 >= 0)) {
      return TRUE;
    }
  }
  return FALSE;
}

NON_MATCH s16 PlaySound(SoundID id) {
#if MODERN
  if (gSongTable[id].ms == gSongTable[SE_ZAKO_STUN].ms) {
    if ((SoundID2 == MUS_DUMMY) || (SoundID2 == SE_ZAKO_STUN)) {
      SoundID2 = id;
    }
    return id;
  }

  if (id == MUS_DUMMY) {
    return MUS_DUMMY;
  }
  m4aSongNumStart(id);
  return id;
#else
  INCCODE("asm/wip/PlaySound.inc");
#endif
}

void stopSound(s16 n) {
  if ((n >= 0) && _isSoundPlaying(n)) {
    m4aSongNumStop(n);
  }
}

NAKED void fadeoutSound(s16 r0, u16 r1) {
  asm(".syntax unified\n\
	push {r4, lr}\n\
	lsls r4, r1, #0x10\n\
	ldr r3, _0800463C @ =gMPlayTable\n\
	ldr r1, _08004640 @ =gSongTable\n\
	lsls r0, r0, #0x10\n\
	asrs r0, r0, #0xd\n\
	adds r0, r0, r1\n\
	ldrh r2, [r0, #4]\n\
	lsls r1, r2, #1\n\
	adds r1, r1, r2\n\
	lsls r1, r1, #2\n\
	adds r1, r1, r3\n\
	ldr r2, [r1]\n\
	ldr r1, [r2]\n\
	ldr r0, [r0]\n\
	cmp r1, r0\n\
	bne _08004636\n\
	lsrs r1, r4, #0x14\n\
	adds r0, r2, #0\n\
	bl m4aMPlayFadeOut\n\
_08004636:\n\
	pop {r4}\n\
	pop {r0}\n\
	bx r0\n\
	.align 2, 0\n\
_0800463C: .4byte gMPlayTable\n\
_08004640: .4byte gSongTable\n\
          .syntax divided\n");
}

// まだ音が終わっていないか
bool32 isSoundPlaying(SoundID n) {
  if (_isSoundPlaying(n) == 0) {
    return 0;
  } else {
    return 1;
  }
}

/*
  ベルトコンベアや時間系エルフのカチコチ音などBGMとは違うがずっと流れている環境音の音量を設定する
*/
void SetStageNoiseVolume(SoundID n) {
  bool32 b = _isSoundPlaying(n);
  if (b != 0) {
    m4aMPlayVolumeControl(gMPlayTable[gSongTable[n].ms].info, 0xffff, 0x100);
  }
}

// ------------------------------------------------------------------------------------------------------------------------------------

const struct ToneData voicegroup000[128] = {
    [0] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08110294,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 216,
    },
    [1] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08110c24,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [2] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08110e88,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [3] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08113154,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [4] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08113840,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [5] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08114c1c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [6] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08115430,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [7] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08117e68,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [8] = {
      type : 8,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081182f4,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [9] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08119ae8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [10] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0811a730,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [11] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0811b9ac,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [12] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08122690,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [13] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081233b0,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [14] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [15] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081239a8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [16] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [17] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [18] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0812548c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [19] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08126dc4,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [20] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08128358,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [21] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0812944c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [22] = {
      type : 8,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0812a598,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [23] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0812d018,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [24] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [25] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0812e01c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [26] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0812fa98,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [27] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081314ac,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [28] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08132a30,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [29] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [30] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08134538,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [31] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08135460,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [32] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [33] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08135df4,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 127,
    },
    [34] = {
      type : 8,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081371c4,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [35] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08137d38,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [36] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08139c10,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 127,
    },
    [37] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0813a868,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [38] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0813acb8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [39] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [40] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0813b20c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [41] = {
      type : 8,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0813c44c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [42] = {
      type : 8,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0813dabc,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [43] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08141fa0,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [44] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08143110,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [45] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08143d90,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [46] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0814508c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [47] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08145da4,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [48] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08148eb8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 165,
    },
    [49] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0814c8a0,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [50] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081501c8,
      attack : 255,
      decay : 0,
      sustain : 206,
      release : 127,
    },
    [51] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0815a450,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [52] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0815ace4,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [53] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0815b6c4,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [54] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0815d274,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [55] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0815e2cc,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [56] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0815f970,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [57] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [58] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08160ea4,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [59] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [60] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [61] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [62] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [63] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [64] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [65] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08161738,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [66] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0816390c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [67] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [68] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08166950,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 127,
    },
    [69] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [70] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081683d0,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [71] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08169a80,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [72] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0816a764,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 127,
    },
    [73] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0816b794,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [74] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0816e040,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [75] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [76] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081702e8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [77] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081735f0,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [78] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08174ca0,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [79] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0817595c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [80] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08176c20,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [81] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08178940,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [82] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0817b640,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [83] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0817c708,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [84] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0817dae8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [85] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0817f1bc,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [86] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0818343c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [87] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [88] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0818508c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [89] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08187bf0,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [90] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08189378,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [91] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0818ac48,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [92] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0818e210,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [93] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0818f1f4,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [94] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08190f1c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [95] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081924bc,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [96] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081969c0,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [97] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08197938,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [98] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [99] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08198864,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [100] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0819a3c8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [101] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0819c514,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [102] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0819d6d8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [103] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081a04c8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [104] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081a12e4,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [105] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081a2ee4,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [106] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081a4af0,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [107] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [108] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081a71f8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [109] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081a91ac,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [110] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081a9e24,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [111] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081aafc4,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [112] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081ac48c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [113] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [114] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081ade90,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [115] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081b23c4,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [116] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081b4a2c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [117] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081b57f0,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [118] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [119] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081b66d8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [120] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081b9144,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [121] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081bb7bc,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [122] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081be04c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [123] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081c1a30,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [124] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081c320c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [125] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081c3e54,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [126] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081c7a64,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [127] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081c97e0,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
};

const struct ToneData voicegroup001[128] = {
    [0] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08110294,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 216,
    },
    [1] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081cbd58,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 127,
    },
    [2] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081cdfa8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 60,
    },
    [3] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081d1640,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 60,
    },
    [4] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081d550c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 60,
    },
    [5] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081d6540,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 60,
    },
    [6] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081d6c70,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 38,
    },
    [7] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081d9f1c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 38,
    },
    [8] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08139c10,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 127,
    },
    [9] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081de3ec,
      attack : 128,
      decay : 0,
      sustain : 255,
      release : 89,
    },
    [10] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081e2060,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 165,
    },
    [11] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08115430,
      attack : 255,
      decay : 0,
      sustain : 206,
      release : 235,
    },
    [12] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081e3bf0,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 165,
    },
    [13] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08115430,
      attack : 255,
      decay : 0,
      sustain : 206,
      release : 0,
    },
    [14] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08115430,
      attack : 255,
      decay : 0,
      sustain : 206,
      release : 204,
    },
    [15] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [16] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [17] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081e87e8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [18] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081ed10c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [19] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081f1bf0,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 127,
    },
    [20] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081f3220,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [21] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081f4cb8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [22] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081ed10c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 127,
    },
    [23] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081f675c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 60,
    },
    [24] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081fbaf0,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 60,
    },
    [25] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081fcc90,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 60,
    },
    [26] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08200260,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 60,
    },
    [27] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0820195c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 188,
    },
    [28] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082066d8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [29] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0820b9dc,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 127,
    },
    [30] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08212ca4,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 127,
    },
    [31] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08216898,
      attack : 13,
      decay : 0,
      sustain : 255,
      release : 226,
    },
    [32] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08216898,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 188,
    },
    [33] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0821a5ac,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 188,
    },
    [34] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_081f1bf0,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [35] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08220d20,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [36] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0822171c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 127,
    },
    [37] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08222680,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [38] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08223c34,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 127,
    },
    [39] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082245c4,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 89,
    },
    [40] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0822a250,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [41] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0822e24c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 89,
    },
    [42] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08231c60,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 89,
    },
    [43] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0823856c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 127,
    },
    [44] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08238d74,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [45] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [46] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0823c4d4,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [47] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0823e9f8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [48] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082410fc,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 165,
    },
    [49] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08245c38,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [50] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0824c608,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [51] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0824e3cc,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 89,
    },
    [52] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08166950,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 127,
    },
    [53] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08250490,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 127,
    },
    [54] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0825403c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [55] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08255ac0,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [56] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08257794,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [57] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0825b8d8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [58] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0825dbbc,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [59] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08261a54,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 165,
    },
    [60] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [61] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [62] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [63] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [64] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [65] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [66] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [67] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [68] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [69] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [70] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [71] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [72] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [73] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [74] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [75] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [76] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [77] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [78] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [79] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [80] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [81] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [82] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [83] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [84] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [85] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [86] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [87] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [88] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [89] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [90] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [91] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [92] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [93] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [94] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [95] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [96] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [97] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [98] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [99] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [100] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [101] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [102] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [103] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [104] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [105] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [106] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [107] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [108] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [109] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [110] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [111] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [112] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [113] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [114] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [115] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [116] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [117] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [118] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08264088,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [119] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [120] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [121] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [122] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [123] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [124] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [125] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [126] = {
      type : 4,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000000,
      attack : 0,
      decay : 0,
      sustain : 12,
      release : 2,
    },
    [127] = {
      type : 4,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000001,
      attack : 0,
      decay : 0,
      sustain : 12,
      release : 2,
    },
};

const struct ToneData voicegroup002[122] = {
    [0] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08110294,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 216,
    },
    [1] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0826602c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [2] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0826908c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [3] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082695cc,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [4] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0826b4f8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [5] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0826e5ec,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [6] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08271668,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [7] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082732e4,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [8] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08276988,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [9] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08278b44,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [10] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082795d8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [11] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0827aa18,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [12] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0827bf30,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [13] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0827dd14,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [14] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0827f8ac,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [15] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0828220c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [16] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08283898,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [17] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08285014,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [18] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08286ec8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [19] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082890b8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [20] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0828bc88,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [21] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0828cde0,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [22] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [23] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [24] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [25] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [26] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [27] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [28] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0828e6d8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [29] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08290124,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [30] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08290cbc,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [31] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08291b24,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [32] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08293e94,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [33] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0829706c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [34] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0829d180,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [35] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082a0a44,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [36] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082a2424,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [37] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082a4dd8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [38] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082a6f40,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [39] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082a7ef4,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [40] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [41] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082a8a6c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [42] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082ab314,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [43] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [44] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082ada38,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [45] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [46] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082aff20,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [47] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082b24ac,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [48] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [49] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082b4314,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [50] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082b7874,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [51] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082b94c4,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [52] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082ba04c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [53] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082badcc,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [54] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082bbf8c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [55] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082bd6f8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [56] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082be9fc,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [57] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082c0e1c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [58] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082c2494,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [59] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082c5820,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [60] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082c8c64,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 127,
    },
    [61] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [62] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [63] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [64] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [65] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08161738,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [66] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [67] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082c8dbc,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [68] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082ca484,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [69] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082cc434,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [70] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082ce0c4,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [71] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082d03e4,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [72] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082d33d4,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [73] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082d6444,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [74] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082d7b98,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [75] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082d9060,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [76] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082d9ee8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [77] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082db714,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [78] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082dcee0,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [79] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082ded00,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [80] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082e0dfc,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [81] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082e3a38,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [82] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082e5ddc,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [83] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082e682c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [84] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082e8da0,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [85] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082e97d0,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [86] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082eaa24,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [87] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082eba40,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [88] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082ed794,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [89] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082ee0c4,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [90] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082f082c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [91] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082f21d8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [92] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082f41a8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [93] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082f50c0,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [94] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082f73dc,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [95] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082f8634,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [96] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082f9214,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [97] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082fa094,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [98] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082fc464,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [99] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082fe94c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [100] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_082ff658,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [101] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0830017c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [102] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_083010a4,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [103] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08302ba8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [104] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08304d4c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [105] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08305e30,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [106] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_083077d8,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [107] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08309a84,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [108] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0830a800,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [109] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08312b68,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [110] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08314f1c,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 127,
    },
    [111] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [112] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08316548,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [113] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08318644,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [114] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08319f40,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [115] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [116] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0831c184,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [117] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0831d4fc,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
    [118] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [119] = {
      type : 1,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : (struct WaveData *)0x00000002,
      attack : 0,
      decay : 0,
      sustain : 15,
      release : 0,
    },
    [120] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_0831e9dc,
      attack : 255,
      decay : 0,
      sustain : 206,
      release : 127,
    },
    [121] = {
      type : 0,
      key : 60,
      length : 0,
      pan_sweep : 0,
      wav : &DirectSoundWaveData_unk_08322e60,
      attack : 255,
      decay : 0,
      sustain : 255,
      release : 0,
    },
};

// clang-format off
const struct MusicPlayer gMPlayTable[MUSIC_PLAYER_LENGTH] = {
    [0] =  {&gMPlayInfo_04, &gMPlayTracks[0],  6, 0},
    [1] =  {&gMPlayInfo_07, &gMPlayTracks[6],  1, 0},
    [2] =  {&gMPlayInfo_08, &gMPlayTracks[7],  1, 0},
    [3] =  {&gMPlayInfo_13, &gMPlayTracks[8],  1, 0},
    [4] =  {&gMPlayInfo_11, &gMPlayTracks[9],  1, 0},
    [5] =  {&gMPlayInfo_01, &gMPlayTracks[10], 1, 0},
    [6] =  {&gMPlayInfo_03, &gMPlayTracks[11], 1, 0},
    [7] =  {&gMPlayInfo_06, &gMPlayTracks[12], 1, 0},
    [8] =  {&gMPlayInfo_12, &gMPlayTracks[13], 1, 0},
    [9] =  {&gMPlayInfo_02, &gMPlayTracks[14], 1, 0},
    [10] = {&gMPlayInfo_09, &gMPlayTracks[15], 2, 0},
    [11] = {&gMPlayInfo_14, &gMPlayTracks[17], 1, 0},
    [12] = {&gMPlayInfo_10, &gMPlayTracks[18], 1, 0},
    [13] = {&gMPlayInfo_00, &gMPlayTracks[19], 1, 0},
    [14] = {&gMPlayInfo_05, &gMPlayTracks[20], 1, 0},
};
// clang-format on

INCDATA("sound/song_table.inc");
INCDATA("sound/direct_sound_data.inc");
INCDATA("sound/song_data.inc");
